fpf_message_box_upgrade += '<h3 class="hndle"><?php _e( 'Get Flexible Product Fields PRO', 'flexible-product-fields' ); ?></h3>';
fpf_message_box_upgrade += '<div class="inside">';
fpf_message_box_upgrade += '<ul>';
fpf_message_box_upgrade += '<li><span class="dashicons dashicons-yes"></span><?php _e( 'Conditional logic for fields', 'flexible-product-fields' ); ?></li>';
fpf_message_box_upgrade += '<li><span class="dashicons dashicons-yes"></span><?php _e( 'Add price to fields', 'flexible-product-fields' ); ?></li>';
fpf_message_box_upgrade += '<li><span class="dashicons dashicons-yes"></span><?php _e( 'New field: Date', 'flexible-product-fields' ); ?></li>';
fpf_message_box_upgrade += '<li><span class="dashicons dashicons-yes"></span><?php _e( 'New field: File Upload', 'flexible-product-fields' ); ?></li>';
fpf_message_box_upgrade += '<li><span class="dashicons dashicons-yes"></span><?php _e( 'Assign field groups to all products', 'flexible-product-fields' ); ?></li>';
fpf_message_box_upgrade += '<li><span class="dashicons dashicons-yes"></span><?php _e( 'Assign field groups to categories', 'flexible-product-fields' ); ?></li>';
fpf_message_box_upgrade += '</ul>';
fpf_message_box_upgrade += '<p><a class="button button-primary" target="blank" href="<?php echo esc_url( apply_filters( 'flexible_product_fields/short_url', '#', 'fpf-settings-widget-upgrade-button' ) ); ?>"><?php _e( 'Upgrade now →', 'flexible-product-fields' ); ?></a></p>';
fpf_message_box_upgrade += '</div>';
